
import { CinematicPrompt, CharacterPassport, CinematicJSON, SettingPassport } from './cinematicSchema';
import { VideoPrompt } from './videoSchema';

export enum NodeType {
  Character = 'CHARACTER',
  Setting = 'SETTING',
  Script = 'SCRIPT',
  Image = 'IMAGE',
  Transformation = 'TRANSFORMATION',
  Video = 'VIDEO'
}

export interface NodeData {}

export interface CharacterData extends NodeData {
  prompt: string;
  image?: string; // base64
  characterPassport?: CharacterPassport;
}

export interface SettingData extends NodeData {
  prompt: string;
  image?: string; // base64
  settingPassport?: SettingPassport;
}

export interface ScriptScene {
  id: string;
  title: string;
  description: string;
  isExpanded: boolean;
  selectedSettingId?: string;
}

export interface ScriptData extends NodeData {
  script: string;
  scenes: ScriptScene[];
  // Cached Enrichment Data
  cachedCharacterId?: string;
  cachedCharacterJson?: any;
  isCharacterLoading?: boolean;
  cachedSettingId?: string;
  cachedSettingJson?: any;
  isSettingLoading?: boolean;
}

export interface GenerationTrace {
  status: 'success' | 'error';
  timestamp: number;
  stepFailed?: 'traversal' | 'architect_json' | 'image_api';
  inputs?: {
    sceneText: string;
    characterText?: string;
    settingText?: string;
  };
  architectOutput?: any; // The JSON generated by the AI
  rawError?: string; // The actual error message
}

export interface ImageData extends NodeData {
  prompt: string;
  image?: string; // base64
  isLoading: boolean;
  error?: string;
  debugTrace?: GenerationTrace;
  
  // Reactive Enrichment Data
  sceneEnrichmentStatus?: 'idle' | 'loading' | 'success' | 'error';
  enrichedSceneJson?: Partial<CinematicPrompt> | CinematicJSON | null;

  // Transformation Pipeline Support
  mode?: 'standard' | 'transformation';
  incomingTransformationData?: {
      json?: Partial<CinematicPrompt> | CinematicJSON | null;
      referenceImage?: string; // base64
  };
}

export interface TransformationData extends NodeData {
  modificationPrompt: string;
  transformationJson?: Partial<CinematicPrompt> | null;
  isProcessing?: boolean;
  referenceImage?: string; // base64 from connected Image Node
}

export interface VideoData extends NodeData {
  promptSchema?: VideoPrompt | null;
  videoUrl?: string;
  isLoading: boolean;
  error?: string;
  startImage?: string;
  endImage?: string;
}

export type AnyNodeData = CharacterData | SettingData | ScriptData | ImageData | TransformationData | VideoData;

export interface Node<T extends AnyNodeData = AnyNodeData> {
  id: string;
  type: NodeType;
  position: { x: number; y: number };
  data: T;
}

export interface Connection {
  id:string;
  fromNodeId: string;
  fromOutput: string | number;
  toNodeId: string;
  toInputIndex: number;
}

export interface ConnectorPosition {
  nodeId: string;
  index: number;
  position: { x: number; y: number };
}

// Persistence Types
export interface Graph {
  id: string;
  name: string;
  nodes: Node[];
  connections: Connection[];
  lastModified: number;
}

export interface ProjectMetadata {
  id: string;
  name: string;
  lastModified: number;
}
